
central:
    hostname: central
    build: central/.
    ports:
        - "8000:8000"
    links:
        - node2
        - node3
    dns:
        - 127.0.0.1
        - 8.8.8.8 
        - 8.8.4.4

node2:
    hostname: node2
    build: node2/.
    ports:
        - "8001:8000"
    dns:
        - 127.0.0.1
        - 8.8.8.8
        - 8.8.4.4

node3:
    hostname: node3
    build: node3/.
    ports:
        - "8002:8000"
    dns:
        - 127.0.0.1
        - 8.8.8.8
        - 8.8.4.4

